package view.Admin;

import controller.AddTicketController;
import model.Ticket;
import java.util.Date;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import view.Shared.LoginForm;

/**
 *
 * @author angelica
 */
public class AddData extends javax.swing.JFrame {

    /**
     * Creates new form AddData
     */
    public AddData() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddData = new javax.swing.JButton();
        isiFlightCode = new javax.swing.JTextField();
        isiDepartureCity = new javax.swing.JTextField();
        isiArrivalCity = new javax.swing.JTextField();
        jamKeberangkatan = new javax.swing.JTextField();
        JumlahTicket = new javax.swing.JTextField();
        Harga = new javax.swing.JTextField();
        isiStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        JLabel BG = new javax.swing.JLabel(); // Tambahkan label untuk background

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAMBAH TIKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, 35));

        btnAddData.setText("Add");
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, -1, 32));

        getContentPane().add(isiFlightCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 163, 30));
        getContentPane().add(isiDepartureCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 163, 30));
        getContentPane().add(isiArrivalCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 163, 30));
        getContentPane().add(jamKeberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 163, 30));
        getContentPane().add(JumlahTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 163, 30));
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 163, 30));

        isiStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "KOSONG" }));
        getContentPane().add(isiStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 163, 35));

        jLabel2.setText("Flight Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Departure City");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setText("Arrival City");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setText("Time");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel7.setText("Tickets");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jLabel10.setText("cw;canei");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -100, 670, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 160, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BG.jpg"))); // Path to your image
        BG.setText("");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 750));

        pack();
    }// </editor-fold>                        

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Get data from input fields
        String flightCode = isiFlightCode.getText();
        String departureCity = isiDepartureCity.getText();
        String arrivalCity = isiArrivalCity.getText();
        Date departureDate = jDateChooser1.getDate();
        String departureTime = jamKeberangkatan.getText();
        int availableSeats = Integer.parseInt(JumlahTicket.getText());
        String status = isiStatus.getSelectedItem().toString();
        double price = Double.parseDouble(Harga.getText());

        // Create Ticket object
        Ticket ticket = new Ticket(flightCode, departureCity, arrivalCity, departureDate, departureTime, availableSeats, status, price);

        // Call controller to add ticket
        AddTicketController controller = new AddTicketController();
        boolean success = controller.addTicket(ticket);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Berhasil menambahkan tiket!");
            new AdminMain().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan tiket!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField JumlahTicket;
    private javax.swing.JButton btnAddData;
    private javax.swing.JTextField isiArrivalCity;
    private javax.swing.JTextField isiDepartureCity;
    private javax.swing.JTextField isiFlightCode;
    private javax.swing.JComboBox<String> isiStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jamKeberangkatan;
    // End of variables declaration                   
}
